### MYHOUSE ###

### define base image
ARG ARCHITECTURE
FROM $ARCHITECTURE/python:2.7-alpine

### define workdir
ENV WORKDIR=/myHouse
WORKDIR $WORKDIR

### install dependencies
RUN apk update && apk add jq && rm -rf /var/cache/apk/*
RUN pip install paho-mqtt requests tinynumpy pyyaml yq

### install myHouse SDK
COPY . $WORKDIR

### define entrypoint
ENTRYPOINT ["sh", "docker/docker-entrypoint.sh"]
CMD ["myhouse"]
