### EGEOFFREY ###

### define base image
ARG ARCHITECTURE
FROM $ARCHITECTURE/debian

### define workdir
ENV WORKDIR=/eGeoffrey 
WORKDIR $WORKDIR

### install dependencies
RUN apt-get update && apt-get install -y jq curl nano wget unzip python-pip expect net-tools usbutils libusb-1.0.0-dev build-essential autoconf cmake pkg-config libtool python-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install paho-mqtt requests tinynumpy pyyaml yq

### install eGeoffrey SDK
COPY . $WORKDIR

### define entrypoint
ENTRYPOINT ["bash", "docker/docker-entrypoint.sh"]
CMD ["egeoffrey"]
