### MYHOUSE ###

### define base image
ARG ARCHITECTURE
FROM $ARCHITECTURE/nginx:alpine

### define workdir
ENV WORKDIR=/usr/share/nginx/html
WORKDIR $WORKDIR

### install myHouse SDK
COPY sdk $WORKDIR/sdk
