### MYHOUSE ###

### define base image
FROM resin/rpi-raspbian

### define workdir
ENV WORKDIR=/myHouse 
WORKDIR $WORKDIR

### install myHouse SDK
RUN apt-get update && apt-get install -y curl wget unzip python-pip expect net-tools usbutils raspi-config raspi-gpio wiringpi libraspberrypi-bin libusb-1.0.0-dev build-essential autoconf cmake pkg-config libtool python-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install paho-mqtt requests tinynumpy
COPY sdk $WORKDIR/sdk
COPY docker $WORKDIR/docker

### define entrypoint
ENTRYPOINT ["bash", "docker/docker-entrypoint.sh"]
CMD ["myhouse"]

