### MYHOUSE ###

### define base image
ARG ARCHITECTURE
FROM $ARCHITECTURE/debian

### define workdir
ENV WORKDIR=/myHouse 
WORKDIR $WORKDIR

### install myHouse SDK
RUN apt-get update && apt-get install -y curl wget unzip python-pip expect net-tools usbutils libusb-1.0.0-dev build-essential autoconf cmake pkg-config libtool python-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install paho-mqtt requests tinynumpy pyyaml
COPY sdk $WORKDIR/sdk
COPY docker $WORKDIR/docker

### define entrypoint
ENTRYPOINT ["bash", "docker/docker-entrypoint.sh"]
CMD ["myhouse"]

